### ISSUE TITLE
Calls to operating system from python cause daemon to segfault.

### ISSUE THREAD

**Issue by rsmeurer0** [rsmeurer0/prescient#2]
As stated on Issue #1. There is a problem in python when using the os.system call to issue a ping.

Don't know yet if it is caused only by the **os.system** or if the **subprocess** call used to issue nmap is also compromised.

**TRY 1:** Reimplement the ping calls to the operating system using subprocess.

**Comment by rsmeurer0** [comment]
As expected subprocess also causes the python program to segfault. Trying now to capture the error message.

**Comment by rsmeurer0** [comment]
Executed in Galileo:
```
$ gdb python3
(gdb) run daemon.py
```

And waited until Segfault.
Output from GDB was:

```
--- google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 146.626/146.626/146.626/0.000 ms
0
CONNECTIVITY: 	Connected to internet
[New Thread 0xb55ffb40 (LWP 4064)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb65ffb40 (LWP 4043)]
PING google.com (216.58.222.110) 56(84) bytes of data.
__deallocate_stack (pd=0xb65ffb40) at allocatestack.c:760
760	allocatestack.c: No such file or directory.
(gdb) 
--- google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 146.504/146.504/146.504/0.000 ms

(gdb) bt
#0  __deallocate_stack (pd=0xb65ffb40) at allocatestack.c:760
#1  0xb7fc3eab in start_thread (arg=0xb65ffb40) at pthread_create.c:427
#2  0xb7e8164e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129
(gdb) 
```

It seems that python doesn't deallocate the memory quite right. (http://stackoverflow.com/questions/29619575/python-list-not-deallocating-memory-after-clearing-the-element-of-the-list)

It seems that python garbage collector should be used in this case. https://docs.python.org/3/library/gc.html

**Comment by rsmeurer0** [comment]
The garbage collector did not work. Problem persists.

Now creating a new branch to use different threading approach. It could be that the constant allocation and deallocation caused by the use of Timer threads is causing segfault.

**Comment by rsmeurer0** [comment]
Found a workarround by using Thread with time.sleep intead of Timer. Another solution was also commented on:

http://stackoverflow.com/questions/39922369/python-segmentation-fault-on-thread-switch
